### ISSUE TITLE
compatibility warning for nodebb v1.1.2

### ISSUE THREAD

**Issue by Lapsus** [mani95lisa/nodebb-plugin-markdown-toc#1]
Hi 
i get a compatibillity warning in the nodebb log. i use version 1.1.2.
The plugin is working though.

regards

**Comment by bydeath** [comment]
An error occur on nodebb 1.10.1
> 2018-10-10T07:08:32.183Z [191] - error:  message=Unexpected token h in JSON at position 66, stack=SyntaxError: Unexpected token h in JSON at position 66
    at JSON.parse (<anonymous>)
    at /usr/src/app/node_modules/nodebb-plugin-markdown-toc/index.js:25:23
    at Array.forEach (<anonymous>)
    at Object.MarkdownToc.parse [as method] (/usr/src/app/node_modules/nodebb-plugin-markdown-toc/index.js:23:11)
    at /usr/src/app/src/plugins/hooks.js:121:12
    at /usr/src/app/node_modules/async/dist/async.js:2516:9
    at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
    at /usr/src/app/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
    at /usr/src/app/node_modules/async/dist/async.js:1046:16
    at Object.reduce (/usr/src/app/node_modules/async/dist/async.js:2515:5)
    at fireFilterHook (/usr/src/app/src/plugins/hooks.js:113:9)
    at Object.Plugins.fireHook (/usr/src/app/src/plugins/hooks.js:93:4)
    at /usr/src/app/src/posts/parse.js:35:13
    at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/usr/src/app/node_modules/async/dist/async.js:5334:5)

**Comment by Lapsus** [comment]
i dont understand your comment?
How is this related to the problem i reported?

**Comment by bydeath** [comment]
Sorry. I mean the plugin doesn't work on nodebb 1.10.1. My last comment shows the error trace info.
